name: Send Daily Update

on:
  schedule:
    - cron: '0 14 * * *' # 14:00 UTC = 9:00 AM CST
  workflow_dispatch:

jobs:
  send_update:
    env:
      USERNAME: ${{ secrets.USERNAME }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TARGET: ${{ secrets.EMAIL_TARGET }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Commit and push changes with github actions bot
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update daily data"
          git push
